name: Lint
on: push
jobs:
  lint:
    defaults:
      run:
        working-directory: ./contract
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install modules
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Format code
        run: npm run format
      - name: Run git status
        run: git status
      - name: Check that lints where commited
        run: test -z "$(git status --porcelain)"
