name: Tests
on: push
jobs:
  contract-tests:
    runs-on: ubuntu-latest
    env:
      wd: "./contract"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Contract Dependencies
        working-directory: ${{ env.wd }}
        run: npm install
      - name: Build Contract
        working-directory: ${{ env.wd }}
        run: npm run build
      - name: Run Contract Tests
        working-directory: ${{ env.wd }}
        run: npm test
