name: Tests
on: push
jobs:
  contract-tests:
    runs-on: ubuntu-latest
    working-directory: ./contract
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Contract Dependencies
        run: npm install
      - name: Build Contract
        run: npm run build
      - name: Run Contract Tests
        run: npm test